return {
 ["content"]={
  ["files"]={
   ["context"]="bin",
   ["context.lua"]="bin",
   ["luametatex"]="bin",
   ["luatex"]="bin",
   ["mtxrun"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-linux-64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2026-01-07",
 ["root"]="selfautoparent:texmf-linux-64",
 ["time"]="20:24:16",
 ["type"]="files",
 ["uuid"]="837e38e7-4566-86e6-3e99-96e9881d9542",
 ["version"]="1.100",
}